### ISSUE TITLE
Свобода слова

### ISSUE THREAD

**Issue by MikhailGorobets** [rms-open-letter/rms-open-letter.github.io#1178]
Столько лет весь мир боролся с  USSR и его цензурой, а теперь...
Ты должен был бороться со злом, а не примкнуть к нему

**Comment by mbklein** [comment]
There's a big difference between "deciding someone's words and actions are inconsistent with the leadership of our organization” and “censorship.”

No one is trying to take away RMS's ability to speak, publish, or express his views.
