### ISSUE TITLE
Expanding scope: revoking copyright assignments

### ISSUE THREAD

**Issue by richfelker** [rms-open-letter/rms-open-letter.github.io#120]
This obviously can't be done in the existing letter, but a proposal I got a lot of positive response to on Twitter was giving a letter like this some teeth by pledging to withdraw copyright assignment if the conditions are not met. If a lot of actual GNU project contributors sign on to that, it would put individual GNU project maintainers in a position of having to accept contributions incompatible with FSF policy, forcing a split from the FSF and extricating them from the FSF's control and influence.

Original proposal thread is here: https://twitter.com/RichFelker/status/1374111037985808398

**Comment by shenlebantongying** [comment]
Just admit that you are jealous about gcc/glibc's position.

GPL is a common argument between so many developers and real open source companies.

Why the  fuck you want to split the community for no actual value? Wasting everyone'e energy and time.

Even they are forked from FSF, those long-time glibc contributors and users will still give no shit to your musl

**Comment by nukeop** [comment]
This is just about sabotaging the free software movement through acts analogous to terrorism and blackmail.

**Comment by richfelker** [comment]
No, it's about saving the movement from someone who cares only about himself and not all the damage he's done to it by his behavior and continued presence.

**Comment by nukeop** [comment]
RMS has already done more for free software than any of the people on the list. You're joining a mob to feel righteous.

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.
