### ISSUE TITLE
Turn off issues on this repo if not interested in discussion or constructive criticism?

### ISSUE THREAD

**Issue by m90** [rms-open-letter/rms-open-letter.github.io#1284]
Seeing this repo now also started deleting issues containing constructive feedback (e.g. #666) why not disable issues (which is a GitHub feature) altogether?

It's very frustrating to see any discussion (the non-offensive kind) being silenced and deleted and it definitely does not create trust of any kind with you as an org.

**Comment by ehashman** [comment]
The issues section is intended for reporting issues.

Discussions are for discussions, which we have not enabled. If you want to have a discussion, the issue tracker is not the place for it.
