### ISSUE TITLE
Minor sorting issues in the "Individuals" section.

### ISSUE THREAD

**Issue by wito** [rms-open-letter/rms-open-letter.github.io#1314]
While people have generally been very good about keeping the list sorted, there are a few names that been misplaced over the course of the building of the list. (I noticed one issue in the W's as I was adding my own signature, doubtless there are others.)

Would it be worth to at some point run a machine sort over it?

**Comment by neilmcgovern** [comment]
Yup. I'll add a new sort when there's a spare minute without new PRs. Sorting while there's outstanding ones will completely mess things up. Thanks for the hint though!

**Comment by neilmcgovern** [comment]
Done in 9cea8a9
