### ISSUE TITLE
Any sources on Tor Project signing the letter?

### ISSUE THREAD

**Issue by imachug** [rms-open-letter/rms-open-letter.github.io#1401]
I didn't manage to find any PR or issue by a Tor developer, why is it listed on the site? If someone sent you a e-mail, please post it publicly with all the headers for verification. Thanks.

**Comment by ehashman** [comment]
Was received via email in https://github.com/rms-open-letter/rms-open-letter.github.io/pull/957

**Comment by imachug** [comment]
Great, what about email headers?

**Comment by lionirdeadman** [comment]
If you don't believe the people here, well, they tweeted about it https://twitter.com/torproject/status/1374754834050654212

**Comment by ehashman** [comment]
Thanks @lionirdeadman !
