### ISSUE TITLE
I think an error slipped in

### ISSUE THREAD

**Issue by lionirdeadman** [rms-open-letter/rms-open-letter.github.io#1502]
With https://github.com/rms-open-letter/rms-open-letter.github.io/commit/b35b12ac08c11965b148aebf96168bf6f0087e62, 
It seems the two top names are well.. not names.

Is this an error or is there someone actually known as `2048 4096`?

**Comment by neilmcgovern** [comment]
They've come in via email, so I think it's deliberate.
