### ISSUE TITLE
Link 15 in Appendix isn't clear

### ISSUE THREAD

**Issue by ericonr** [rms-open-letter/rms-open-letter.github.io#155]
From https://github.com/rms-open-letter/rms-open-letter.github.io/blob/3a8d402da7d5a7c4496aafe48a0de307762bfa18/appendix.md

1. you might want to link directly to https://www.gnu.org/philosophy/kind-communication.en.html , otherwise one can get the translated version of the page, which might not have exactly the same contents
2. from a quick read, it isn't clear to me how the current text is still transphobic, though it could definitely be worded better. I would suggest explaining what's wrong with their language/wording/message so more people can understand what's wrong with it

The current version is:

> Footnote

 > Honoring people's preferences about gender identity includes not referring to them in ways that conflict with that identity. For instance, not to use pronouns for them that conflict with it. There are several ways to avoid that; one way is to use gender-neutral pronouns, since they don't conflict with any possible gender identity. One choice is singular use of “they,” “them” and “their.” Another choice uses the gender-neutral singular pronouns, “person,” “per” and “pers,” which are used in Information for Maintainers of GNU Software. Other gender-neutral pronouns have also been used in English.

**Comment by ehashman** [comment]
Because many people have signed, we will not retroactively change the contents of the site.

**Comment by ericonr** [comment]
@ehashman IMO it would also serve a strategic point in not getting the appendix dismissed or partly dismissed, but I see what you mean. Maybe you could include an explanation here, at least? So people who search a bit might find it.

**Comment by ericonr** [comment]
It would seem I'm not the only one... #401
