### ISSUE TITLE
Regarding stallman.org links in appendix.md

### ISSUE THREAD

**Issue by tonejito** [rms-open-letter/rms-open-letter.github.io#1555]
I was checking the [`appendix.md`][appendix.md] file RAW view and saw that some links point to `stallman.org` and others to `web.archive.org`. For example:

```
[10]: https://web.archive.org/web/20210319210116/https://stallman.org/archives/2016-jul-oct.html#31_October_2016_(Down's_syndrome)
[11]: https://stallman.org/archives/2015-jul-oct.html#21_October_2015_(Mistaking_a_fetus_for_a_baby)
[12]: https://stallman.org/archives/2016-mar-jun.html#23_April_2016_(Fetuses_with_Downs_syndrome)
[13]: https://web.archive.org/web/20161107050933/https://www.stallman.org/archives/2016-jul-oct.html#31_October_2016_(Down's_syndrome)
```

Should all links point to `web.archive.org` and pull a copy of the current contents of `stallman.org` in case the source is wiped?. What do you guys think?.

[appendix.md]: https://raw.githubusercontent.com/rms-open-letter/rms-open-letter.github.io/main/appendix.md

**Comment by lionirdeadman** [comment]
I think that would be a good idea.

**Comment by ehashman** [comment]
No objections from me to updating the links to web.archive.org links.

**Comment by tonejito** [comment]
Do you think it's better to apply `web.archive.org` to **ALL** links or just `stallman.org` links?

**Comment by ehashman** [comment]
I think all should probably be web.archive.org links so that they are snapshotted as they look now.

**Comment by mollydb** [comment]
I am pro all the links being from web.archive.org. I'd be happy to put some time into this, especially if other people work on it as well.

**Comment by ziggythehamster** [comment]
Nobody asked for my opinion, but I agree with all of the above as well. I had this thought last night, but thought it might have been out of line to suggest it (perhaps the point is to show that these are _current_ things that despite the coverage are still up, and I didn't want to be incorrectly seen as someone questioning the authors with all of the off-topic hate/spam last night).

**Comment by tonejito** [comment]
@mollydb I opened a PR (#1681) to address this, all the changes are progressively done in commits in case you want to drop something:

The last commit (`dee001741b54b856b94f59e27d2ecc826113ebf8`) is the most aggressive since it renamed the links but proper care was taken when renumbering them.

Anyway, please check it.

**Comment by neilmcgovern** [comment]
I've now merged this.
