### ISSUE TITLE
Fake signature?

### ISSUE THREAD

**Issue by lionirdeadman** [rms-open-letter/rms-open-letter.github.io#1693]
The signature of `Chinese Developers 🇨🇳 中国开发者（Diemcoin.Network)` might be fake, they also signed the support letter.

**Comment by lionirdeadman** [comment]
It is the same person who PR'ed here (https://github.com/rms-open-letter/rms-open-letter.github.io/pull/1032) and the person who commited this file in support letter (https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_data/signed/chinese.yaml)

**Comment by ehashman** [comment]
Probably just advertising, I'll remove it and they can re-add with an explanation if desired :)
