### ISSUE TITLE
fork jekyll/minima to rms-open-letter/minima and set remote_theme to allow PR (for stuff like i18n)

### ISSUE THREAD

**Issue by jukefr** [rms-open-letter/rms-open-letter.github.io#1819]
EDIT: i think the best idea would be to fork the minima theme under the same namespace and set the `remote_theme` so that we can make PRs directly for stuff like impleting a i18n dropdown

**Comment by jukefr** [comment]
maybe add links to header via instead
```
header_pages:
  - index.es.md
  - index.fr.md
etc
```
but it might get messy fast

i dont really know how to show the available translations and make them accessible without them being at the end of 2K+ signatures on the index

**Comment by jukefr** [comment]
maybe it would be wiser to just switch jekyll theme to something that natively supports i18n to have the least hastle possible

from quick searching it seems the current one did not care for i18n https://github.com/jekyll/minima/pull/60#issuecomment-361354096 support sadly

**Comment by jukefr** [comment]
i think the easiest would be to fork the theme and include it in the repo, afaik you can do that

then change the header code to add a language switcher dropdown that gets fed from `_config.languages` probably

i can start work on this and make a pr if you want

**Comment by jukefr** [comment]
if you could fork https://github.com/jekyll/minima pretty please
under the rms-open-letter namespace
then update _conf to `theme: rms-open-letter/minima` https://docs.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll
that should work
and also allow people to make PR for issues like this one directly

**Comment by neilmcgovern** [comment]
Done!
