### ISSUE TITLE
Add "Institutional affiliation is provided for identification purposes only and does not constitute institutional endorsement."

### ISSUE THREAD

**Issue by baumanj** [rms-open-letter/rms-open-letter.github.io#182]
It seems to me more useful to have people include the organizations they're affiliated with, but without this sort of disclaimer, I think many folks would be hesitant to do so. Other open letters do this, see http://blogs.edf.org/texascleanairmatters/files/2013/08/Scientist_Letter_OzoneMay_25_2010.pdf as an example.

**Comment by coderanger** [comment]
As people have already signed this specific content, it will be not be changed retroactively.

**Comment by baumanj** [comment]
I'd certainly agree you can't *add* a clause implying institutional endorsement after the fact, but I'd see this as a clarification of the existing signatures not implying it. To say nothing just invites ambiguity. If any institutions want to make statements, they should be singing the letter as the organization or putting out their own statement, no?

**Comment by ehashman** [comment]
I have no issue with this and I reached out to the other initial signers who agreed it's implied but may as well be explicit. Let me add it.
