### ISSUE TITLE
[theme] make the i18n dropdown a11y compliant

### ISSUE THREAD

**Issue by jukefr** [rms-open-letter/rms-open-letter.github.io#1853]
It is currently not at all accessible and only exists as MVP to allow people access to the languages and contributors to add new ones.

https://github.com/rms-open-letter/minima

making this issue here to make things easier

**Comment by ehashman** [comment]
Hi @jukefr,

We used a default GitHub page theme (see https://pages.github.com/themes/). The repo is maintained at https://github.com/jekyll/minima

We could potentially fork the theme and take some carry patches but it would be much better to fix upstream.

I mistakenly assumed that GitHub default themes would be a11y-compliant, apparently not :sweat:

**Comment by jukefr** [comment]
Oh yeah there was already a fork done to enable a language dropdown that i made a PR for, however I am a backend so I am not familiar with what needs to be done for a11y.

i18n was out of the scope of the theme apparently https://github.com/jekyll/minima/pull/60#issuecomment-361354096 and this was the easiest way to get it done

**Comment by ehashman** [comment]
Ohhh I see, this is specific to the dropdown. Happy to track this issue here.

**Comment by jukefr** [comment]
This is the specific file that deals with the dropdown for clarity.

https://github.com/rms-open-letter/minima/blob/master/_includes/i18n-dropdown.html
