### ISSUE TITLE
[theme] implement a "list" module that gets fed from list.md to show list on every language index file instead of only english

### ISSUE THREAD

**Issue by jukefr** [rms-open-letter/rms-open-letter.github.io#1855]
the idea would be that people who sign the letter would do so on `list.md` for example
then in the theme we can simply include said list into every index (no matter the language) that gets rendered

https://github.com/rms-open-letter/minima

**Comment by ehashman** [comment]
I suspect fixing this is not a good use of our time :) I am going to close but we can reopen if we decide this is worth doing.
