### ISSUE TITLE
misleading citation in appendix

### ISSUE THREAD

**Issue by mpizzzle** [rms-open-letter/rms-open-letter.github.io#1892]
The quote from the appendix: _"On at least one occasion RMS likened having a child with Down’s syndrome to having a pet. [14](https://web.archive.org/web/20210325014348/https://stallman.org/archives/2016-jul-oct.html#31_October_2016_(Down's_syndrome))"_

Unlike the majority of the points in the appendix, this one doesn't seem to quote anything RMS said in the citation. here is the citation in full:

_"31 October 2016 (Down's syndrome)_
_A noninvasive test for Down's syndrome eliminates the small risk of the old test. This might lead more women to get tested, and abort fetuses that have Down's syndrome._

_According to Wikipedia, Down's syndrome is a combination of many kinds of medical misfortune. Thus, when carrying a fetus that is likely to have Down's syndrome, I think the right course of action for the woman is to terminate the pregnancy._

_That choice does right by the potential children that would otherwise likely be born with grave medical problems and disabilities. As humans, they are entitled to the capacity that is normal for human beings. I don't advocate making rules about the matter, but I think that doing right by your children includes not intentionally starting them out with less than that._

_When children with Down's syndrome are born, that's a different situation. They are human beings and I think they deserve the best possible care."_

I see no reference to animals, pets etc. I'm not claiming that RMS didn't make the comparison at some other point in time, but I think a fair reading of the citation doesn't support the claim that he did. I would recommend either updating the citation or removing the sentence.

**Comment by jukefr** [comment]
https://twitter.com/popey/status/793384010718248960

![image](https://user-images.githubusercontent.com/2154296/112489547-d2628600-8d7e-11eb-8cd8-ac06146f85bd.png)


/thread

**Comment by jukefr** [comment]
https://web.archive.org/web/20161101101115/https://stallman.org/archives/2016-sep-dec.html

**Comment by mpizzzle** [comment]
Thanks for this. or this one:

https://web.archive.org/web/20161107050933/https://stallman.org/archives/2016-jul-oct.html#31_October_2016_(Down's_syndrome)

I think the citation needs to be updated then.

**Comment by mollydb** [comment]
Thanks for the catch!
