### ISSUE TITLE
README could include details on how to add a name without renumbering

### ISSUE THREAD

**Issue by jessamynwest** [rms-open-letter/rms-open-letter.github.io#2000]
I'm using the github editor and am not very tech savvy about it. I read the README which is specific about making sure adding your own signature does not renumber everyone "_please double check that it doesn't renumber everyone. Each signature should start with a "1. "_" 

I definitely understand those words, but I've tried a few things and everything I have tried results in everyone beneath my name getting renumbered. If there is a trick to getting the github editor to not do this, it would be a helpful addition to the README file. I'm aware I can email my name in which is what I'll do if I can't figure this out. Thanks!

**Comment by Admicos** [comment]
My trick was to go to the very first character of the next line and press enter to create a new empty line. Then I just typed in "1. My Name" and it seemed to work properly. You might want to try that

**Comment by jessamynwest** [comment]
Thank you @Admicos , that totally worked, I'll add an edit to the README.

**Comment by jessamynwest** [comment]
Got advice, figured it out, edited README
