### ISSUE TITLE
Signing

### ISSUE THREAD

**Issue by System0x20** [rms-open-letter/rms-open-letter.github.io#2030]
While working hard on Persian translation to PR a clean and accurate translation, May I add a bunch of signs to the thing in a single PR? I asked all of them if I'm allowed to do so

**Comment by ehashman** [comment]
Hi @System0x20, it'd be easier to do it in separate PRs I think!

**Comment by System0x20** [comment]
Ok then we wont do that. Just me and contributors to the translation. Thanks
