### ISSUE TITLE
Clarify statement about transphobia in appendix

### ISSUE THREAD

**Issue by ele38** [rms-open-letter/rms-open-letter.github.io#2085]
Reading the fragment you quoted from Stallman "there are various ways to express gender neutrality in third-person singular pronouns in English" and his article about gender-neutral pronouns, I interpret it as him enforcing gender-neutral pronouns, while using whatever synonym you think is better. I think the transphobia in the latter should be explained in the appendix since it's not clear why it's transphobic, since he is advocating for respecting people's pronouns.

Please note this issue is not meant as a discussion whether it is a transphobic statement or not, I'm only pointing out it should be clarified why this is considered a transphobic statement to make it clear for future readers of the letter.

**Comment by ehaliewicz** [comment]
I was also curious about this, because I looked at the earliest version of the document on archive.org, and it still simply seemed that he thought using other gender-neutral pronouns was preferable, not that he was trying not to use them at all.

**Comment by hackerncoder** [comment]
I would like to add that both 15 and 16 link to https://web.archive.org/web/20210325014959/https://www.gnu.org/philosophy/kind-communication.html

**Comment by mollydb** [comment]
I think these are good questions, but we won't address them in the appendix at this time. It's already been signed by a number of people, and it's unfair to them to make changes beyond adding citations.

**Comment by MattMadness** [comment]
Richard Stallman has never shown any signs of being transphobic. In fact he constantly advocates for trans rights in his political rss feed. I think that is should be removed because you are misinforming the people that he is actually transphobic when really he is not the slightest.

**Comment by mollydb** [comment]
> I would like to add that both 15 and 16 link to https://web.archive.org/web/20210325014959/https://www.gnu.org/philosophy/kind-communication.html

Good catch! Thank you. Fixed to a link referencing the original posting.

**Comment by ehashman** [comment]
Please see #155 #401.
