### ISSUE TITLE
Email privacy for contributions

### ISSUE THREAD

**Issue by jul** [rms-open-letter/rms-open-letter.github.io#2113]
Because I signed the letter I received (as other people signing this letter) a weird mail.

Maybe using github that leaks our email is not a good idea ?

<details>
> Thank you for your contribution to the destruction of freedom of speech
> and freedom of thought. Your help in establishing a fascist dictatorship
> where people are persecuted for their thoughts is appreciated.
>
> Thanks to people like you, the communist revolution of 1917 in Russia
> became possible. By virtue of you contribution, the humanistic values of
> the criminal liberal society will finally be trampled into the mud for
> good. And then the rule of the tolerant conformal majority will prevail and
> never parish.
>
> Thank you for your invaluable contribution to the future of conformity.
>

Since I can be trollish I answered « Heil Stalin ! »
</details>

EDIT(@ehashman): folded email into details section

**Comment by ehashman** [comment]
Hi @jul, This is the default behaviour of git, where all commits include an author email address. I'm surprised that GitHub does not redact/hide emails by default.

GitHub has a handy blog post about [how to maintain email privacy while using GitHub](https://github.blog/2017-04-11-private-emails-now-more-private/) that you can refer to, particularly if you are using the web editor.

If you are using git on the command line, after cloning the repo, you can use the following commands to set your name and email for your commits:

```bash
git clone $repo
cd $repo
git config user.name $your_name
git config user.name $email_you_want_on_the_commit
```

You can verify the email on a commit using `git show`:

```bash
ehashman@red-dot:/tmp/rms-open-letter.github.io$ git show
commit 9efccb4f6ff1ed6fa771721f711e7dabb48113e4 (HEAD -> main, origin/main, origin/HEAD)
Author: NAME <EMAIL>   <-- email here
Date:   Thu Mar 25 10:36:45 2021 -0700
```


Note that GitHub will not provide you with credit for a contribution if the email on the commit doesn't match one associated with your GitHub account.

**Comment by ehashman** [comment]
Let me add this to the README and I'll close this (but keep the issue pinned for visibility).
