### ISSUE TITLE
open invitation to create new terminology and direction for our movement

### ISSUE THREAD

**Issue by Be-ing** [rms-open-letter/rms-open-letter.github.io#2148]
In [discussion on the fediverse](https://fosstodon.org/web/statuses/105942614831431178) regarding this letter and recent events, I have come to the conclusion that our movement could benefit from new terminology and direction. I am proposing the term "communal software" for this. I have written an initial draft of a document explaining my thoughts and I invite your comments on [Codeberg](https://codeberg.org/CommunalSoftware/website/pulls/1).

**Comment by neilmcgovern** [comment]
This isn't something this letter is designed to address, it's fairly narrowly focused. Sorry about that.

**Comment by Be-ing** [comment]
I understand. I didn't mean to suggest that this letter should address this. I am just putting a link in this repo to invite anywho who is interested to join the discussion.
