### ISSUE TITLE
adding a thanks section

### ISSUE THREAD

**Issue by jul** [rms-open-letter/rms-open-letter.github.io#2274]
This project is a lot of work, you are probably pressed by trolls and it must be tiring.
Volunteers are doing a great job and answer in a thoughtful and fast way.

Maybe it's the rock-star syndrom that poisons the well of collective initiatives, however can you do something to acknowledge the fact you are amazing ?

**Comment by ehashman** [comment]
Hi @jul,

Thank you for the kind words. This is a big team effort. I think the quality of our collective work stands on its own. :blush:
