### ISSUE TITLE
On what really harms free software

### ISSUE THREAD

**Issue by Natureshadow** [rms-open-letter/rms-open-letter.github.io#2285]
Hi,

just thinking loudly:

With the FSFE freezing its collaboration with the FSF, projects signing open letters to effectively disassemble the FSF and the GNU project altogether, it seems we are officially at war.

With all due respect to everyone who has been offended by Richard Stallman, feels oppressed by him, or is negatively affected by his views — every single such person has to be heard, their fears and sorrows been taken into account, and appropriate action been taken. As such, I am in full support of requiring the FSF board to instate an investigation committee, take letters from anyone affected, and hear these cases (including rms' position).

What I do **not** support is forcing the disintegration of the FOSS community, even less in such crucial times. The COVID pandemic forces evryone to digitise the hell out of them and their organisations, and every action that weakens the FOSS movement in this ciritical process certainly does more harm to the ecosystem than a single person on any FOSS body's board ever could. Thus, I consider those responsible for this, in my opinion, thoughtless action harmful to the FOSS ecosystem.

As already said, I am in full support of an investigation committee, and would immediately sign an open letter requesting the FSF to instate one (including a helpful list of requirements for this committee).

Thanks for listening!

P.S.: On a side note, hosting this thing on GitHub, which explicitly discriminates against parts of the community and is itself harmful to the FOSS ecosystem as a whole, is at least a bit weird.

**Comment by Natureshadow** [comment]
@neilmcgovern This must be the openness and inclusiveness you advocate for ☺!

**Comment by gururise** [comment]
@Natureshadow Sorry, but your ideology is not in line with the backers of this repo, therefore you will be silenced and cancelled.

I hope everyone stands up to these bullies and sees them for what they are: idealogues.

**Comment by ehashman** [comment]
> What I do not support is forcing the disintegration of the FOSS community, even less in such crucial times. 

I strongly agree.
