### ISSUE TITLE
consider adding a note warning potential signatories of harassment

### ISSUE THREAD

**Issue by void-witch** [rms-open-letter/rms-open-letter.github.io#2460]
unfortunately, there's been some harassment of signatories (i.e. #2113), and attempts at drumming up harassment on the "rms-support-letter" (https://github.com/rms-support-letter/rms-support-letter.github.io/issues/3296). i think it should be made clear to people looking to sign this that there's serious potential for harassment for signing this letter. it'll probably scare some people away, but i think they have the right to know that harassment *is* already occurring

**Comment by void-witch** [comment]
ah hell, it's tagged that support-letter thread. my bad, i didn't realize it would do that. i've got most of them blocked but there might be issues

**Comment by Odyssey346** [comment]
I think we can do that through using the Greet GitHub action on PRs.

**Comment by void-witch** [comment]
i would like to add that the previously-mentioned issue thread has now had members attempting to screenshot and link this thread to block evade. with that, the few people on twitter spouting constant harassment, and the multiple 4chan threads, this has gone from "potential harassment" to just "harassment"

**Comment by Bandie** [comment]
Your idea's good. 

But for those whose faith in humanity is already destroyed it is obvious already. :)

**Comment by neilmcgovern** [comment]
Added in ce6f6ef
