### ISSUE TITLE
Dutch translation: "Frequently known as"

### ISSUE THREAD

**Issue by JC5** [rms-open-letter/rms-open-letter.github.io#2483]
The original English letter reads "frequently known as RMS". This is a bad stretch from "also known as" and has no value. The history of his initials and his use of them is not picked up on in the letter. 

Leave it if you will, but it translates into the Dutch sentence "vaak bekend als" and in my opinion it's not a strong opening for this letter. I was hoping to be able to adjust some small things in the Dutch translation of the letter: not just translating the words but also reordering a sentence "here and there".

That would mean however a less literal translation of the English words and idioms.

Also calling upon @DankDumpster, @catrope and @ehashman for their opinion.

**Comment by catrope** [comment]
Sounds good to me. You're right that "vaak bekend als" is not natural wording. It would be good to change that in the Dutch letter at least

**Comment by neilmcgovern** [comment]
I'm happy for translations not to be literal transliterations - that's the point of them :)

**Comment by ehashman** [comment]
I don't speak Dutch, happy to take patches :smile:

**Comment by JC5** [comment]
Thanks for your feedback. Let me know what you think.

https://github.com/rms-open-letter/rms-open-letter.github.io/pull/2503
