### ISSUE TITLE
Rephrase "Sudanese law" part of the appendix

### ISSUE THREAD

**Issue by Artoria2e5** [rms-open-letter/rms-open-letter.github.io#2529]
In https://github.com/rms-open-letter/rms-open-letter.github.io/pull/2498#discussion_r602785228 I mentioned that the current English text

> He compares United States law to Sudanese law in saying that “US laws that define ‘rape’ to include voluntary sex with under N years of age (where N varies)” and that “both laws falsify the meaning of ‘rape.’”

is not written enough in that it does not highlight the also important issue that is a disregard of marital rape, and makes it read like the comparison to some African country is the main problem.

The thing is, well, I still haven't figured out a good way to fix it. Part of me wants to nuke the N-year quote and just replace it with the phrase "age of consent", while the other part says that I can fix it with a very small change by replacing "Sudanese law" with "Sudanese law's criminalisation of marital rape".

**Comment by ehashman** [comment]
Because so many people have signed, we will not retroactively change the contents of the site.

(I agree this is awkward, and there have been some small edits with notes, but at this point I don't think this can or should be fixed.)
