### ISSUE TITLE
Reconsider accusations of transphobia?

### ISSUE THREAD

**Issue by coolreader18** [rms-open-letter/rms-open-letter.github.io#401]
To start: I am trans, and I'm not demanding this based on purely my opinion; I'd like to intend this as a discussion for people who feel strongly about this, as I truly don't feel that the linked articles are really transphobic and I'd like to hear from people that do.

Also, I understand that you've been saying that you won't change the content as many people have already signed, but I feel like removing parts is less likely to cause somebody to change their mind about signing than adding? In any case:

Although the parts regarding gender in the GNU Kind Communication Guidelines aren't *perfect*, they do seem to be written with the intent to be accepting of gender identities (and even plurality, in the [genderless pronouns](https://stallman.org/articles/genderless-pronouns.html) article). I feel the quote "you do not have to use ‘they’" is taken out of context a bit, it's simply suggesting the bespoke person/per/pers pronouns that the FSF uses in the context of encouraging people to use gender-neutral pronouns when writing about an indeterminate person.

The main problem I see is to encourage use of gender-neutral pronouns for any person, which *can* be harmful - calling a binary trans person "they", for example, is generally considered misgendering. However, it seems to come from a place of ignorance rather than malice, as the core of the gender guidelines ("call them by the names they use, and honor their preferences about their gender identity", "[don't] use pronouns for them that conflict with it") do seem to be accepting of diverse gender identities. I'm assuming, and perhaps charitably, that RMS simply didn't realize that using gender-neutral pronouns *can* in fact conflict with a persons identity.

So, I think the links listed in the appendix are damning enough that it's unnecessary to muddy the waters with accusations of transphobia.

**Comment by ehashman** [comment]
Because many people have signed, we will not retroactively change the contents of the site.

I appreciate the concerns you're voicing, and thank you for sharing.

**Comment by void-witch** [comment]
hey remember when the fsf fired a trans employee for reporting transphobic harassment? remember when stallman defended that, and then made leah rowe's life absolute hell when leah pulled libreboot out of gnu?

downplaying transphobia, defending actions that punish trans people instead of transphobes, and then creating a harassment campaign against a trans person and never apologizing for any of it is absolutely without question something that makes you a transphobe

**Comment by ChadFacts** [comment]
^ No, none of that makes a person a transphobe.

**Comment by Jan200101** [comment]
I cannot speak on the entire thing but I remember the libreboot part very well
>  remember when stallman defended that, and then made leah rowe's life absolute hell when leah pulled libreboot out of gnu?

it was leah rowe that went out of their way to attack the FSF and pull libreboot from GNU while acting as libreboot without consulting any of the other people

the entire thing and how it was dramatized can be seen on the
[old blog post](https://web.archive.org/web/20161207233755/https://libreboot.org/gnu/) (DISCLAIMER: OLD AND NO LONGER REPRESENTS THE AUTHORS VIEWS) and the [unity blog post](https://libreboot.org/news/unity.html)
