### ISSUE TITLE
Proposal: Boycott of supporting companies

### ISSUE THREAD

**Issue by mariogrip** [rms-open-letter/rms-open-letter.github.io#454]
To make this more effective, I propose a boycott of any supporting patrons of fsf, with this let those companies know whats going on and hopefully put pressure on fsf. 

See https://www.fsf.org/patrons

**Comment by Be-ing** [comment]
https://fosstodon.org/web/statuses/105940500359519036

**Comment by xapienz** [comment]
And also boycott emacs, gcc and all people who use them?

**Comment by brown121407** [comment]
> And also boycott emacs, gcc and all people who use them?

Maybe even start using Windows and Visual Studio as a sign of protest! That will show them!

**Comment by appetrosyan** [comment]
@xapienz , Thanks a lot! neither emacs nor GCC are RMS's pet projects, haven't been for a while. As a user of both, I'd propose a reverse boycott of the software of the people who have signed this open letter... if anyone actually used it.

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.

**Comment by ShadowJonathan** [comment]
> @xapienz As a user of both, I'd propose a reverse boycott of the software of the people who have signed this open letter [...]

Be ready to boycot (as of 56ef328):
- XOrg
- Wayland
- GNOME
- Debian (and also ubuntu and derivatives)
- (open)SUSE
- Arch
- Wikipedia (Wikimedia)
- GCC
- GPLv3
- Kubernetes
- Ansible
- Red Hat products (such as RHEL)
- Mozilla (and firefox)
- Alpine Linux
- Nix
- OBS
- LibreOffice
- Fedora
- C++
- KDE
- Google
- LXC
- The Linux Kernel
- Void Linux
- Elementary OS
- GNU
- OpenStack
- Python (+Django, NumPy and PyPi)
- The Open Source Initiative
- Matrix
- XMPP
- Ruby
- CNCF
- Lutris
- OpenZFS
- NetBSD
- FreeBSD
- OpenWrt
- The FSFE
- Gentoo
- GStreamer
- Ada
- Musl libC
- Apache
- Linux Containers
- The Open Infrastructure Foundation
- Node.JS (and all apps/servers built with it)
- Electron (and all apps built on it)

Good luck, i'd say :)
