### ISSUE TITLE
Merging PRs in Batches

### ISSUE THREAD

**Issue by ehashman** [rms-open-letter/rms-open-letter.github.io#47]
We will be merging PRs in ~hourly batches starting 2021-03-23 19:00 UTC. Don't fret if we haven't got to your PR yet, we are still accepting signatures at this time.

If your PR gets closed and your name was *not* properly added, feel free to send an email (digitalautonomy at riseup.net) as we are using a small amount of automation to generate the names list and it might miss names if not correctly formatted.

---

Edit: As of 2021-03-24 00:30 UTC, we are merging in best-effort batches rather than hourly. Cheers.

**Comment by julian-klode** [comment]
I'm wondering, do you have tools to resolve the conflicts? Like every merge creates conflicts with every other, which is hardly optimal.

**Comment by ItzSwirlz** [comment]
> I'm wondering, do you have tools to resolve the conflicts? Like every merge creates conflicts with every other, which is hardly optimal.

GitKraken is helpful for fast-forwarding

**Comment by galessandroni** [comment]
Giacomo Alessandroni

**Add personal signature**

**Comment by luiztheblues** [comment]
Just asking: how could i sign this?
Is it open to anyone in the community or just for important people (like project leaders and mantainers)?

**Comment by whyadamsalt** [comment]
> Just asking: how could i sign this?
> Is it open to anyone in the (open source/libre) community or just for important people (like project leaders and mantainers)?

It should be open to anyone.

**Comment by ehashman** [comment]
I'm going to close this as the initial flood has subsided and we've been able to keep up with the pace of merging 1-by-1 now :)
