### ISSUE TITLE
Targeting ideas instead of persons

### ISSUE THREAD

**Issue by m90** [rms-open-letter/rms-open-letter.github.io#666]
I support the ideas behind this letter 100%. However when reading it, I am reluctant to sign because of the following line:

> Our communities have no space for people like Richard M. Stallman

which - to me - is crossing the line when it comes to excluding persons by name, when we should exclude by behavior. This is very well phrased here:

> These sorts of beliefs have no place in the free software, digital rights, and tech communities.

I don't have a brilliant proposal for how to change it either (if it's even possible to change it now that people signed), but maybe I myself would feel much happier about signing this with a line like:

> Our communities have no space for the behavior exposed by Richard M. Stallman

**Comment by ojnny** [comment]
Please take a moment to reconsider. Do you really want an environment where anyone deemed 'problematic' by a woke mob is purged and have their lives destroyed? This is the behaviour of ideological extremists and have no place in any healthy community.

**Comment by Punkoivan** [comment]
>when we should exclude by behavior.

in IT world we should exclude by knowledge and contributions and shouldn't do "witch-hunt"

**Comment by appetrosyan** [comment]
> Our communities have no space for people like Richard M. Stallman

This isn't particularly fair. RMS is a fruitful contributor to the world. He just happens to bring a lot of negatives with him. Instead of phrasing this as a "We have no place for the person who made our work possible" it should be phrased in terms of his behaviour. 

In particular, I think it's quite possible to set a set of rules, abiding by which would be the terms of his continued presence on the FSF board. In other words, a gentlemens' agreement about what he will do, what he should not do, in a legally binding fashion.

**Comment by m90** [comment]
> in IT world we should exclude by knowledge and contributions

This is a dangerous misconception / myth I think: Being a brilliant engineer does not make you exempt from adhering to certain norms in your daily conduct. Just like being a perfectly behaved person does not make you a brilliant engineer. Both are important, engineering is a technical as well as a social endeavor, you will need to be skilled in both to master it.

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.

Also, a huge thank you to those in here who have kept discussion civil, unlike in other ones.

**Comment by m90** [comment]
In case the phrasing is frozen and there is no more discussion to be had about it (which sounds reasonable) it would seem like a fair thing to do to also close issues that call for stricter measures (boycott et al) instead of only the ones that loosen things.

**Comment by neilmcgovern** [comment]
Indeed. I'll go prune those too.
