### ISSUE TITLE
Hypocritical "Letter"

### ISSUE THREAD

**Issue by ChadFacts** [rms-open-letter/rms-open-letter.github.io#667]
I would like to point out the hypocrisy of ones who created this. 

First, on another issue, you locked it for being "too heated," when it was a very simple discourse. Two people explaining their points and reasoning without any inflammatory language, or as you locked it for being "too heated." The issue about boycotting is in essence about attacking livelihoods and people for either A) not knowing what you're bothered about, B) who are just trying to do their work.

Secondly, you even hid comments on the aforementioned issue for being disruptive content. Disruptive? Sorry, you're allowed to make a request to a foundation openly without any censorship to it, openly talk about boycotting those who aren't involved, etc. and someone can't give necessary reasons to why this is inappropriate? In a polite manner with fair points? That's plain hypocritical. If you're afforded freedom of speech to attack those support FOSS? That's insanely hypocritical, even. Attacking those who support essentially freedom of software with your freedom of speech while attempting to hide others' freedom of speech?

Lastly, you're dragging in those who are uninformed to sign? Randoms who follow bandwagons on Twitter to be a part of cancel culture because they enjoy seeing others fail and suffer at the hands of the collective hive mind of Twitter? If that's not blatantly disgusting, I don't know what is. 

If you lock this without responding, that's just showing everyone the reality behind the curtain.

**Comment by ChadFacts** [comment]
I would also like to add for a fourth point, in not only attacking a single member of the board, but the entirety of the board, it casts the notion that you're not against the person. You're against the entire foundation. You're not looking to cancel a single member, you're trying to cancel the entire foundation. You're trying to weaken the foundations that uphold FOSS, essentially. There's no other reason for you to attack more than one person.

**Comment by neilmcgovern** [comment]
https://xkcd.com/1357/

**Comment by ChadFacts** [comment]
That's literally not what freedom of speech means. That's what legal freedom of speech means. Aren't you, y'know, meant to have a brain?
