### ISSUE TITLE
My personal opinion

### ISSUE THREAD

**Issue by Anachron** [rms-open-letter/rms-open-letter.github.io#672]
I don't know how we got to this point. But seriously, when did we start to ask a board of people to remove someone from a position that he is perfectly able to handle, I'd go as far and even say he is the perfect guy for the job, especially because of his strong opinions on freedom and rights.

The world is currently fighting a lot of battles on many ends, whether its `white vs black`, `male vs female`, the fight with `corona` and/or many other things. Many, many opinions and views can be build and shared here,- whether you agree with them or not. 

However, these opinions and/or views should be allowed in a free society. Do we want to live in a society where the governor can't privately say that he hates coke without getting a lawsuit? Do we want to live in a society where all public people can't have their own opinions without everybody trying to be hurt? Honestly I bet most people who signed this letter haven't even started to understand the point that RMS was trying to make. They're just hurt and want their "justice".

I wouldn't want to live in a society where I could be fired for my own opinions on something that has nothing to do with my job. And especially not in one where you would even ask a whole board to resign. This is madness, and not in a good sense. 

Disclaimer (Since I guess this is needed here, which is a quite sad state): 
I am neither agreeing nor disagreeing with RMS opinions. I am simply trying to open your mind on what implications this has.

**Comment by ChadFacts** [comment]
I agree. I disagree entirely with the one person being removed and hold entirely the same opinions you do. Even mentioning for an entire board to remove just completely defeats the purpose of the foundation in the first place and is just pure anarchist bandwagoning. Who would fill the positions? Are they suggesting they'd be good candidates to fill every position? If not, then who? And how would the community trust them to fill the positions or do they want the positions? It's madness.

**Comment by ojnny** [comment]
I agree. This kind of oversensitive, hyper-political, unprincipled no-good behaviour of the intersectionalists is nothing but, well, 'problematic'.

**Comment by Anachron** [comment]
@neilmcgovern what a very sad state that we close issues that we do not agree with, no matter how honestly and truthful they're written.
