### ISSUE TITLE
Collect signatures, or at least collect statistics about those opposing this movement

### ISSUE THREAD

**Issue by imachug** [rms-open-letter/rms-open-letter.github.io#676]
I feel like you are exaggerating and your arguments are not only fallacious, but are against common sense. None of us are ideal; Stallman is in no special in this aspect. Yesterday you targeted Stallman only, now you're calling for removal of the whole FSF board; you could equivalently point at me or about one half of the whole development community--I'd like to see what you'll manage to find online about me. You want more and more victims to sacrifice until only you --a few hundered 'developers'-- are left, 'nice' and all. Sorry to aim to prove you wrong, but you can't just kill all bad people.

Don't judge a developer for his personality, judge them by their professionalism. Pretend that you managed to fire RMS--what next? Would that reduce violence a tiny bit?--no. Would that be a huge problem for the entire open source/free software community?--yes. This open letter was apparently written by @mollydb; sorry for argumentum ad hominem, but I don't feel like you should have been the one to call against Stallman--the founder of FSF. Without him we wouldn't have free software at all and would live with non-free commerical bloat. Do you really think you'll be able to replace him at least as good? A few great developers did sign the letter, but most others are not CEOs or anyone near important.

I'm sure there are lots of free software developers opposing this point of view and believing that you are willing to undermine the whole free software movement for your very selfish goals. Please collect the list of developers that are against this movement.

**Comment by neilmcgovern** [comment]
Feel free to collect a list of people who agree with you, but we won't do this for you.

**Comment by slesru** [comment]
neilmcgovern , I will :-D

**Comment by catzcod** [comment]
This major FSF issue has been closed without a fix. Closing dangerous issues without reason is community rights violation.

**Comment by em92** [comment]
Probably Stallman's supporters would like to subscribe to this pr https://github.com/rms-open-letter/rms-open-letter.github.io/pull/791

**Comment by imachug** [comment]
@neilmcgovern Okay, I understand that you don't like and don't support my point of view, but can you keep this issue open for a while? If you really believe you're right, then this won't do any harm, correct?

**Comment by Clasen00** [comment]
I am not a misogynist, not an ableist or transphobic. But in my opinion, a person can be removed for his qualifications that do not correspond to the position, for sabotage, etc.
But you cannot displace because of BELIEF. Because displacing because of views is exactly the same discrimination. If not worse ...

**Comment by appetrosyan** [comment]
https://gitlab.com/a-p-petrosyan/rms-libre-letter

**Comment by GrimReaperFloof** [comment]
https://github.com/rms-support-letter/rms-support-letter.github.io maybe take a look at this, guys
