### ISSUE TITLE
Formatting issue in signature list

### ISSUE THREAD

**Issue by bramhaag** [rms-open-letter/rms-open-letter.github.io#781]
The latest commit has introduces a formatting error, see [here](https://github.com/rms-open-letter/rms-open-letter.github.io/commit/b3483cf7078fd8d647024a82434fc0c7be538b45#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5R758). This line is rendered as a table on the website.

**Comment by neilmcgovern** [comment]
Thanks, fixed in df801e9
