### ISSUE TITLE
RMS has returned!

### ISSUE THREAD

**Issue by dvz0** [rms-open-letter/rms-open-letter.github.io#794]
I'm happy that RMS has returned to the Free Software Foundation board of directors, and I hope, it is forever.

**Comment by Anachron** [comment]
Your comment is going to be closed in a matter of minutes, because we're not allowed to voice our concerns of this letter here.

**Comment by dvz0** [comment]
> Your comment is going to be closed in a matter of minutes, because we're not allowed to voice our concerns of this letter here.

I don't care, I gave my opinion. Let the tolerationists suck.

**Comment by ChadFacts** [comment]
And apparently legal freedom of speech is defined equivalently to actual freedom of speech. Kek. Ironic on how they can abuse their freedom of speech and platforms of bandwagoning idiots but we can't even say one thing to them.

**Comment by neilmcgovern** [comment]
https://xkcd.com/1357/

**Comment by ChadFacts** [comment]
^ Yes, yes, you're still proving your point that you're an idiot.
