### ISSUE TITLE
Overcome discriminations using discriminations?

### ISSUE THREAD

**Issue by Drag13** [rms-open-letter/rms-open-letter.github.io#811]
Hi guys!

I think this letter has one bug. It's build to overcome the discriminations (please correct me if I am wrong) but it actually discriminating the person because of his thoughts, but not of objective precincts. 

This makes me really sad because a lot of efforts were already put in to make this world more friendly to people that have different thoughts/sex/whatever. With this letter you are ruining all of that efforts, you going back to the dark times when we were not free to express the thoughts when you have to belong to a certain religion or be banished. 

Right now, it seems that if I want to see a more diverse, more friendly world I have to argue with you because freedom of thoughts is one of the most important things we have in the world.

What event worse, your letter scares me because it actually means that if some person wants simply work, he/she have to have the right thoughts, but who will decide what is right? If we start judging the thoughts this we will end-up in Germany 40th. I don't believe that this is your target. But when I see issues closed without any reason I start to doubt.

So if you think that Stollman is not good enough, please try to find another argument that not based on his personal thoughts.

**Comment by neilmcgovern** [comment]
https://xkcd.com/1357/

**Comment by Drag13** [comment]
@neilmcgovern This is a very good point and of course you are free to refuse to deal with a person you dislike. But you can't say that you want to discriminate against that person because he discriminates whatever. This is just hypocrisy, and leads to ruining the basic principle diversity is built on. Probably you understand that and this means to the question - if diversity is not your target, what is the target then? 

And closing the issue without any dialog? This world you want to live in?

**Comment by appetrosyan** [comment]
@neilmcgovern , So... the first amendment doesn't protect you from being criticised... by myself... and very justifiably called a hypocrite... by many others.

**Comment by Drag13** [comment]
I really do hope to see the clear answer here or clear silence which, actually will be the answer.

**Comment by Jan200101** [comment]
> https://xkcd.com/1357/

This is a HORRIBLE take on this
Yes someone spreading Nazi propaganda should be kicked out but this isn't even on the same level as that
There is an attempt at discussion that is closed, laughed at and disregarded
You are essentially showing people who are willing to have a discussion the door just so you can preserve your echo chamber

**Comment by neilmcgovern** [comment]
Feel free to write about this and criticise me on your own blog. That's freedom of speech.
