### ISSUE TITLE
Is this censorship?

### ISSUE THREAD

**Issue by imachug** [rms-open-letter/rms-open-letter.github.io#848]
You've limited conversation to collaborators on my previous issue #676. Why did you do that, did I break any rule?

**Comment by imachug** [comment]
Sorry for spam everyone, let's collaborate on this repository now: https://github.com/rms-support-letter/rms-support-letter.github.io. Please spread the word.

**Comment by Jan200101** [comment]
It can be argued that the people in charge of the repo are free to silence any conversation they are not willing to listen to
but this has very easily created a bunch of bad takes and the ending of discussions

@neilmcgovern seems to have no interest in letting discussion happen

**Comment by Drag13** [comment]
My was also [locked ](https://github.com/rms-open-letter/rms-open-letter.github.io/issues/811)without any dialog (except "shut up" kinda link)

**Comment by appetrosyan** [comment]
And this one https://gitlab.com/a-p-petrosyan/rms-libre-letter

**Comment by Jan200101** [comment]
#811 is great to mention for this
after being called out for shutting down discussion citing that no one needs to listen to you this response was given
> Feel free to write about this and criticise me on your own blog. That's freedom of speech.

It is true that the people behind this are free to do as they please it does show that there is an unwillingness to let people partake in discussion of the opposite site which is essentially hurtful to the goal of the letter and shows the true goal of this, not to spread awareness or reach a meaningful goal but to gather a mob

**Comment by imachug** [comment]
@appetrosyan Let's all collaborate in one single place. There's a big repo here: https://github.com/rms-support-letter/rms-support-letter.github.io. What about using it instead?

**Comment by appetrosyan** [comment]
@imachug The only problem I have is that GitHub is Microsoft-owned, and anything going against the "woke" mainstream, may cause us issues. I'll reconfigure my repo to be a mirror of yours, but I'd strongly urge people not to put all eggs into one basket.

**Comment by Jan200101** [comment]
> @imachug The only problem I have is that GitHub is Microsoft-owned, and anything going against the "woke" mainstream, may cause us issues. I'll reconfigure my repo to be a mirror of yours, but I'd strongly urge people not to put all eggs into one basket.

that is an understandable concern but as it stands Github is simply a bigger platform with a wider spread and splitting the support letter up will create confusion.
Perhaps it is best to just keep a backup until Microsoft decides to act

**Comment by neilmcgovern** [comment]
I have no interest in discussing this further here. If you want to collaborate elsewhere, feel free
