### ISSUE TITLE
The whole form seems unfortunate

### ISSUE THREAD

**Issue by psychoslave** [rms-open-letter/rms-open-letter.github.io#909]
Hello,

I will join #666 on its point that the topic with no doubt is worth our consideration, but the actual form of this document is very problematic. 

Being upset by an unacceptable behaviour is understandable. However, to my mind, letting anger direct the way the document is formulated will not add any credit to its cause. On the contrary, the whole tone seems in direct contradiction with its intention of fostering more respectful environments in Free Libre Open Works (FLOW).

Bellow I share with you my thoughts of alternative formulations, so you can see that I am not by any mean trying to silent criticism by some rhetorical means. Any behaviour that deal with the safety on our contribution spaces  is a serious topic. And serious topic deserve our attention in a way that won't confuse speed with precipitation.

First the title. Here there is a choice to make on the goal. If the goal is that M. Stallman leaves the board, the title might stay as is I guess. If the open letter is seriously asking for whole board to resign, then the title should better reflect that and be something like "an open letter to the FSF".

# Paragraph 1
>Richard M. Stallman, frequently known as RMS, has been a dangerous force in the free software community for a long time. He has shown himself to be misogynist, ableist, and transphobic, among other serious accusations of impropriety. These sorts of beliefs have no place in the free software, digital rights, and tech communities. With his recent reinstatement to the Board of Directors of the Free Software Foundation, we call for the entire Board of the FSF to step down and for RMS to be removed from all leadership positions.

This is missing some context of who, or in name of who, this open letter is written. Context matter. While I firmly believe that this is not a defamation campaign leaded by someone with an hidden agenda to discredit the FSF, it's good to recall who is behind the initiative. Of course, people from who you already gathered signatures also give information on that. But to state it right from the beginning would make no harm.

So here is a suggestion of alternative formulation:
>We, the undersigned, react here to the recent reinstatement of M. Stallman to the Board of Directors (BoD) of the Free Software Foundation (FSF). M. Stallman has been publicly well known for behaviours which, among other serious accusations of impropriety¹, include misogynism, ableism, and transphobism, as shown in more precise references bellow. We believe that our community must foster through open and safe spaces where people can confidently expect to be treated in respectful manner, no matter their age, beliefs, gender, political affiliation, sexual orientation, nationality, and so on, as long has they show the same level of respect to other. We affirm firmly that anyone who acts in contradiction with these goals will not be welcome in our community, and by no mean should such a person be given a position to BoD of the FSF. We thus require the immediate withdraw of M. Stallman from all its leadership positions. [Furthermore we call for the entire Board of the FSF to step down.]²

¹ A more exhaustive list might come as a footnote here, or this formulation might just be withdrawn as any of the other pointed behaviour should be enough to make the point without relying on additional allegation less firmly backed.
² To me, that's a whole different matter. The text as it is don't make clear why everybody should leave. If there is collusion at play, I think that it should be stated explicitly, and if all members are implied, proofs should be given for all of them.

# Forword

I hope that you will perceive that my feedback is by no mean a way to discourage you to pursue further your actions that I understand as the result of a will to make our contribution spaces more welcoming and safe for everybody, as long as people who want to participate do it in a manner that foster mutual respect.

This comment is placed under CC-0, feel free to reuse and adapt any part as you want.

# Additional comments

It seems that the text greatly involved between the moment I started to write this feedback and the time I submit it. Initially I was about to provide feedback on each paragraph. An etherpad would seems more appropriate if the document is supposed to evolve quilckly, wouldn't it?

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.

**Comment by psychoslave** [comment]
Well, unfortunately I wasn't able to contribute earlier as I wasn't aware of it.

Cheers
