### ISSUE TITLE
Is there a gitlab option?

### ISSUE THREAD

**Issue by terceranexus6** [rms-open-letter/rms-open-letter.github.io#939]
I already PR my signature, but is there a _gitlab_ copy for reaching out people who doesn't have github? If not, is it okay of I use the same introduction (but not the signatures of course) for it?

Thanks.

**Comment by amitai** [comment]
@terceranexus6, there is not a gitlab copy. Hope this helps.

**Comment by mollydb** [comment]
Hi! There were some technical problems with GitLab close to our publication time, so we switched to GitHub at the last minute.

**Comment by terceranexus6** [comment]
> Hi! There were some technical problems with GitLab close to our publication time, so we switched to GitHub at the last minute.

Is it okay if I create a similar copy from my personal gitlab or from the gitlab of a digital rights association I organize?

**Comment by CyberTailor** [comment]
Gitlab is just as unethical as Github
https://git.sdf.org/humanacollaborator/humanacollabora/src/branch/master/gitlab-dot-com.md

**Comment by terceranexus6** [comment]
> Gitlab is just as unethical as Github
> https://git.sdf.org/humanacollaborator/humanacollabora/src/branch/master/gitlab-dot-com.md

Not speaking about ethics, just the fact that some people won't reach this repository and yet they will reach gitlab, I was mentioning the availability.

**Comment by hiddeco** [comment]
Imho, it makes no sense to create another repository and have two identical letters signed by different people, if you do not have a GitHub account, you can still send an email to the advertised address in the letter / on the website and it will be added to the list.

**Comment by smurfix** [comment]
@hiddeco The idea would be to cross-push the repository to both. In practice this is not a problem, there'll be one list not two.

**Comment by hiddeco** [comment]
My comment was regarding

> is it okay of I use the same introduction (but not the signatures of course) for it?

**Comment by mollydb** [comment]
I would suggest that people interested in signing and not using github email digitalautonomy at riseup.net.

**Comment by terceranexus6** [comment]
> I would suggest that people interested in signing and not using github email digitalautonomy at riseup.net.

awesome

**Comment by amitai** [comment]
Molly I completely agree
