### ISSUE TITLE
How to sign he should retain positions held? 

### ISSUE THREAD

**Issue by Motophan** [rms-open-letter/rms-open-letter.github.io#940]
I disagree entirly with deplatforming a person responsible for the gnu license from the foundation he started. Nor would it do anything than sate your appetite for blood. 

If you disagree with him, fine. Know that what he accomplished will likely eclipse anything you will ever accomplish in your entire life and his legacy will live on past the cancel culture.

**Comment by Jan200101** [comment]
the support letter is available here https://github.com/rms-support-letter/rms-support-letter.github.io
