### ISSUE TITLE
Improve the appendix

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [rms-open-letter/rms-open-letter.github.io#951]
Regarding https://rms-open-letter.github.io/appendix

My suggestions and issues with it:

- Remove the selamjie article as it does a dis-service to this petition by making you seem as dishonest, since the main argument of this article stems from a failed reading comprehension that the author has refused to correct. There have been multiple other inaccuracies to it that were debunked over time (such as the door sign one).

- Please elaborate on """In the original publication of the GNU Kind Communication Guidelines, he said “there are various ways to express gender neutrality in third-person singular pronouns in English; you do not have to use ‘they.’”"". The quote seems.. correct? xir is an older gender-neutral pronoun that I remember, the one that stallman invented is another. I do not see what is transphobic about this. I checked both the old and the new version of the guidelines. I am sure that you would not have put that if you had not detected some issue with that text so it is probably a misunderstanding on my part. Would you mind elaborating on it?

- Regarding """RMS decries that this is not “sexual assault” because “‘assaulting’ presumes that he applied force or violence”"". RMS is focusing about how most people would perceive the words "sexual assault". The first image that comes to mind when someone tells me "sexual assault" is someone getting forcefully pushed in order to be kissed, it gives the impression that something that did not happen actually did.

- Regarding ""where he also shares his views on minors being “entirely willing.”"". He does not seem to make that argument in the linked post. Maybe you put the wrong link? In this specific one he was generally dissatisfied with the vagueness of news articles and again being annoyed with how people often use certain legally/technically correct words that give a different impression to the reader. Just like in the previous case.

- Regarding "He regularly and repeatedly makes comments about “the dishonest law that labels sex with adolescents as ‘rape’ even if they are willing". Same as above.

- Regarding """He compares United States law to Sudanese law in saying that “US laws that define ‘rape’ to include voluntary sex with under N years of age (where N varies)” and that “both laws falsify the meaning of ‘rape'"""". Again, same as above. Most people think of someone being physically forced or threaten with violence in order to perform sexual acts when someone says rape. He is just an old dude that wants the article that he reads to be honest and clear on their meaning. 

- Regarding "Stallman has previously expressed opinions that were consistent with the inaccurate portrayal". A link here would be useful.

- Regarding "but the most plausible scenario is that she presented herself to him as entirely willing". Well, it would be in the interest of Epstein to tell her to act willing or else. I mean, he would not like the people going to his islands to know that he runs a sex trafficing ring. After all his intention was to blackmail people, not be blackmailed himself. So what RMS says seems likely and even if it was not.. is it that bad to make hypotheses?

- Regarding """Of a woman having sex with a minor, he said “I wish an attractive woman had ‘abused’ me that way when I was 14.”""". Including this seems extremely distasteful. Kink-shaming is not cool. Let people have their fantasies.

- Regarding """He defended pedophilia, in general, in saying that “there is little evidence to justify the widespread assumption that willing participation in pedophilia hurts children.”"". He apologized and withdrew that. I would suggest mentioning it in that page. I presume that you did not know but if you did and did not mention it then that would be dishonest.

- He directly addressed child pornography by saying that “making such photos should be a crime, and is a crime, but that is no reason to prohibit possessing copies of the photos.”

afaik, the common reasoning that such images are prohibited is because some think that they could turn people into pedophiles (similar to the argument that "gay culture" or "gay pornography" turns people gay) or that it might cause children to be sexually assaulted (kinda similar to the games cause violence argument). There might be more reasons that I am not aware of but this is not as clear as a case that you make it out to be. It is certainly worth debating over.

- Regarding the part about Down’s syndrome, currently it kinda reads like a "pro-life" (read: anti-choice) complain. It would use some tidying up but you can make a case out of it.

I think that it would be better on focusing on harassment (online, verbal, or physical) committed by stallman instead rather than saying that he should be removed for posting about random opinions, thoughts, and comments. I believe that this would give more legitimacy on your campaign.

Thank you for reading my rambling. I hope that it was of use :3

**Comment by mollydb** [comment]
>     * Regarding """He defended pedophilia, in general, in saying that “there is little evidence to justify the widespread assumption that willing participation in pedophilia hurts children.”"". He apologized and withdrew that. I would suggest mentioning it in that page. I presume that you did not know but if you did and did not mention it then that would be dishonest.

Do you have a citation?

**Comment by M-i-k-o-t-o** [comment]
@mollydb Here it is https://stallman.org/archives/2019-jul-oct.html#14_September_2019_(Sex_between_an_adult_and_a_child_is_wrong)

**Comment by neilmcgovern** [comment]
Folks, unfortunately the phrasing of the letter is now frozen as it's been signed by a number of people. I don't think there's any more fruitful discussion to be had in this issue as we won't be changing it at this stage, sorry.

Also, a huge thank you to those in here who have kept discussion civil, unlike in other ones.

**Comment by M-i-k-o-t-o** [comment]
@neilmcgovern  This issue concerns the appendix which contains arguments on why people should sign the letter and changing it would not modify the contents of the letter itself. Thank you for your kind reply though.

**Comment by mollydb** [comment]
> @mollydb Here it is https://stallman.org/archives/2019-jul-oct.html#14_September_2019_(Sex_between_an_adult_and_a_child_is_wrong)

I'm going to make a PR to add an edit (with a note) to the appendix. Thank you.
